server:
  port: 8080
spring:
  ai:
    deepseek:
      api-key: sk-c7a7acd9a03c4a2385a7a98f03a3a759
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
          temperature: 0.8
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode # OpenAI 服务的访问地址，这里使用的是阿里云百炼
      api-key: sk-0f2d9e334aaf471ea180cafb0f2126d6
      chat:
        options:
          model: qwen-turbo # 模型名称
          temperature: 0.7 # 温度值
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
